
version: "3.9"

services:
  risk-game:
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    image: risk-game:latest
    container_name: risk-game-container
    user: "${USER_NAME}"
    env_file:
      - .env
    volumes:
      - .:/app
      - ${GAME_RESULTS_HOST_PATH}:/shared-game-results
      - ./custom_startup.sh:/usr/local/bin/custom_startup.sh
      - ./data/rclone-config:/home/${USER_NAME}/.config/rclone
      - ./data/rclone-cache:/home/${USER_NAME}/.cache/rclone
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - USER_NAME=${USER_NAME}
      - RISK_GAME_RESULTS_DIR=/shared-game-results
    depends_on:
      - qdrant
    entrypoint: ["/usr/local/bin/custom_startup.sh"]
    command: ["tail", "-f", "/dev/null"]

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    # Bind-mount to project-local directory
    volumes:
      - ./data/qdrant/:/qdrant/storage
    restart: unless-stopped
